### ISSUE TITLE
Neuer Posttype rrze_designsystem

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-designsystem#1]
Es soll ein neuer Posttype angelegt werden (Id: rrze_designsystem) mit derzeit folgenden Feldern:

- Titel (Default)
- Content  (Default)
- Artikelbild (Default)
- HTML (Textarea)
- CSS/SASS (Textarea), plus Auswahltyp CSS oder SASS.
- JavaScript (Textarea)
- Screenshot Preview
- Demo- und Downloadlinks
   - optionaler Link zu CodePen
   - optionaler Link zu GitHub  
   - optionaler Link zu Figma
   - optionaler anderer Link + Eingabe Linktext

**Comment by lukasniebler** [comment]
Vereinigt in #21
