### ISSUE TITLE
Nice to Have

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-designsystem#11]
- [ ] Definieren von Breakpoints im Backend und Ausgabe einer Tabelle über einen Block:
![Bildschirmfoto 2024-06-07 um 09 51 34](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/a59971e2-d952-48ab-9366-e6b7b9645ab0)
- [ ] Definieren von Farben im Backend und Ausgabe einer Swatch-Übersicht über einen Block (+ Hex-Farbtöne?)
![Bildschirmfoto 2024-06-07 um 09 55 34](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/6b7a8e0f-1f1f-4226-a372-22a2000f07b0)
![Bildschirmfoto 2024-06-07 um 09 56 55](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/d5845baf-6afa-4984-a94a-6bf70a5f6d7a)

- [ ] Definieren von Abständen / Spacing inkl. CSS Token und Ausgabe einer Tabelle als Block:
![Bildschirmfoto 2024-06-07 um 09 52 58](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/2914951d-bbd2-4360-91b2-b014e363fd8d)
- [ ] Ähnliche Tabellen:
![Bildschirmfoto 2024-06-07 um 09 54 11](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/8d54c8b1-e75d-46de-818f-6e38011d397c)

![Bildschirmfoto 2024-06-07 um 09 54 43](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/19aeba8a-80db-4359-ba56-234f67dfe169)
![Bildschirmfoto 2024-06-07 um 09 55 02](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/de33bfcc-ba4f-4cf5-8560-f788e53dacfb)

![Bildschirmfoto 2024-06-07 um 09 56 05](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/93394d0d-22f1-46ff-9abe-e82bead79502)

![Bildschirmfoto 2024-06-07 um 09 56 17](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/b3877e16-560c-4805-b294-96558f595387)

![Bildschirmfoto 2024-06-07 um 09 56 35](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/a1dee71c-fb5d-4919-b41e-c10dfa7bcaa3)

**Comment by xwolfde** [comment]
Das sind Datentables?

Frage ist eher: Soll es automatisch generierbare Tables geben, wenn die Werte wie in den Beispielen berechenbar sin? Und wenn ja, in welcher ML-Version?
