### ISSUE TITLE
Status / Label System

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-designsystem#12]
https://ux.redhat.com/design-code-status/
![Bildschirmfoto 2024-06-07 um 09 57 56](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/1215af36-9ad5-4033-86f1-66e73d806a47)

![Bildschirmfoto 2024-06-07 um 09 58 11](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/2c81118c-9929-4223-a80a-e8cd21f3ebb8)

Auf CPT der einzelnen Komponenten:
![Bildschirmfoto 2024-06-07 um 09 58 34](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/b638da47-ba48-4156-b670-4ac0f6806960)

![Bildschirmfoto 2024-06-07 um 09 58 52](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/e96f2bc5-a617-49b6-87b9-27951d60a0b0)

**Comment by xwolfde** [comment]
Ist das ein Umsetzungshinweis, ist das ein Umsetzungstodo,... ? Erwächst aus diesem Hinweis ein Issue, wenn ja, welcher un dzu welchen Milestone. Bitte definieren.
