### ISSUE TITLE
Als Redakteur möchte ich eine Möglichkeit Schriftarten und Schriftgrößen in einer geordneten Tabelle auszugeben

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-designsystem#13]
## User Story
Als Redakteur möchte ich eine Möglichkeit im Backend Schriftarten und die zugehörigen Schriftgrößen zu pflegen, um diese später im Frontend als Tabelle auszugeben

## Definition of Done
- [ ] Es gibt eine Möglichkeit die Schriftarten im Backend zu pflegen und zu verwalten
- [ ] Vorschau der Schriftart, Token name, Value, Use Case sind mindestens enthalten
- [ ] Eine Kopier-Funktion, um z.B. eine hinterlegte CSS-Variable zu kopieren, wäre cool
- [ ] Es gibt eine einfache Möglichkeit die Tabelle im Content-Bereich einzusetzen (z.B. Block oder Shortcode)

## Referenzbilder
![image](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/892ad1dd-0ecf-48c5-b915-77d89789ee91)
https://ux.redhat.com/foundations/typography/

**Comment by xwolfde** [comment]
Bitte dies deutlicher erklären. Der einleitende Text lässt denken, dass es darum geht das man Schriften mit dem Plugin auf die Webseite des Designsystems hochläd und anzeigen können kann. Die Tabelle drunter  als Referenz zeigt aber nur Werte, die wie in #14 und #15 eigentlich eine Datentable sind.

**Comment by lukasniebler** [comment]
In #23
