### ISSUE TITLE
Als Redakteur möchte ich eine einfache Möglichkeit, um Breakpoints zu definieren und auszugeben

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-designsystem#14]
## User Story
Als Redakteur möchte ich eine einfache Möglichkeit, um Breakpoints zu definieren und auszugeben

## Definition of Done
- [ ] Einfache Verwaltung im Backend, um neue Breakpoints anzulegen
- [ ] Visuelle Ausgabe im Frontend zu den verschiedenen Breakpoints
- [ ] Möglichkeit die CSS Token-Name's gleich zu kopieren

## Referenzbild
![image](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/0bc496b6-7c9c-4ffb-b075-426129da0ee4)
https://ux.redhat.com/tokens/breakpoint/

**Comment by xwolfde** [comment]
Wo ist der Unterschied zu #15 ? Hier handelt es sich eigentlich doch nur um Definition von CSS properties, bzw. Variablen.
Nur eben mit der Überschrift Breakpoints.

**Comment by lukasniebler** [comment]
In #23
