### ISSUE TITLE
Als BrandOffice möchte ich die Möglichkeit, das Designsystem an zukünftige Situationen flexibel anzupassen

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-designsystem#15]
Als BrandOffice möchte ich die Möglichkeit, das Designsystem an zukünftige Situationen flexibel anzupassen und zum Beispiel Tokens um neue Elemente erweitern.

## Definitionen of Done
- [ ] Eine Möglichkeit eigenständig weitere Design-Tokens anzulegen und zu befüllen. (Zum Beispiel könnte es sein, dass neben Typographie und Breakpoints ein neues Token hinzukommt (z.B. Border), welches den gleichen Aufbau nutzt. (CSS-Variable, Verwendungszweck, etc.
- [ ] Die Möglichkeit SVG's oder kleine PNG's als Grafiken für die einzelnen Elemente zu hinterlegen
- [ ] Eine Ausgabemöglichkeit über Block / Shortcode für die neu definierten Tokens

## Referenzbild
Die folgenden Token folgen alle dem gleichen Aufbau. Es wäre cool, wenn man im Backend selbst definieren kann, welche zusätzlichen Token man benötigt.
![image](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/2b9dc090-72c7-4d2a-b6f2-40cc17c84255)
![image](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/a1c743ae-e2bb-4060-8269-04d22082ca2c)
![image](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/de35235c-ec17-47ad-8718-1868a18a4288)
![image](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/435bd940-fc0c-4ef0-86d0-e98426164b1e)
![image](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/5950c9a4-8ec8-49cb-ae4c-8dd2e8f56838)

**Comment by xwolfde** [comment]
Da man das alles auch von Hand machen kann, sind das alles Funktionen die einen das Leben bei der EIngabe erleichtern - Nice to have- aber keine Grundfunktionen. Daher verschieben in V2.

**Comment by lukasniebler** [comment]
In #23
