### ISSUE TITLE
Als Redakteur möchte ich eine einfache Möglichkeit Farbpaletten im Backend anzulegen und zu verwalten

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-designsystem#16]
## User Story
Als Redakteur möchte ich eine einfache Möglichkeit Farbpaletten im Backend einzulegen und zu verwalten, damit Sie im Frontend dan geeigneter Stelle ausgespielt werden können.

## Definition of Done
- [ ] Es gibt eine einfache Möglichkeit Farben im WP-Backend anzulegen und zu verwalten
- [ ] Die Ausgabe ist bequem über einen Block oder Shortcode möglich
- [ ] Eine Farbvorschau wird im Frontend mit ausgegeben
- [ ] Für Farbpaletten können sowohl HEX, als auch CMYK / LAB-Farbwerte hinterlegt werden

## Referenzbild
![image](https://github.com/RRZE-Webteam/rrze-designsystem/assets/58593037/a321c632-d9d1-4f8e-97c6-24564bbb070d)
https://ux.redhat.com/tokens/color/

**Comment by xwolfde** [comment]
Brauchen wir das wirklich in V1? Das ist doch eher eine Nice to Have Funktion, aber nicht eine die V1 dann schon braucht. IMHO: Alles was Nice to Have ist, kann nur erst ab V2 kommen

**Comment by lukasniebler** [comment]
Für mich ist das eine Grundfunktionalität… Wenn wir alle Variablen und Farben händisch pflegen können wir uns das Plugin auch komplett sparen…

**Comment by xwolfde** [comment]
Dann definiere eine Verwaltung einer Datentable(z.B. in Form eines speziellen CPTs)  als Grundfunktion. Aber nicht spezielle Tables, die man dann danach eben als Redakteur anlegt und befüllt.

**Comment by lukasniebler** [comment]
In #23
