### ISSUE TITLE
Ausgabe-Layout

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-designsystem#2]
Bei der Ausgabe eines INhalts des Posttypes soll der Titel und der Content immer angezeigt werden, während Screenshot Preview, HTML, CSS, JavaScript und die Links in Tabs gezeigt werden.

Die Felder HTML, CSS, JavaScript sollen mit Hilfe eines Sytanx-Highlightning dargestellt werden und auch eine Copy to Clipboard-Funktion des Contents enthalten. Hierzu gibt es ggf. andere Plugins, die hierzu eingebunden werden können.

Wenn möglich sollte es ein Link "Edit/Copy to CodePen" geben, damit man dort dann das HTML/CSS/JS als neues Codepen ediieren und sehen kann. (Schnittstelle von CodePen hierzu unklar => Prüfen ob das geht).

**Comment by xwolfde** [comment]
Orientieren kann sich die Ausgabe an die anderer Designsysteme (Komponentendarstellung):
- https://designsystem.webstandards.ca.gov/components/page-navigation/readme/
- https://m2.material.io/components/lists
- https://developer.apple.com/design/human-interface-guidelines/buttons
- https://designsystem.digital.gov/

**Comment by lukasniebler** [comment]
In #22 Nutzung von CodePen in v2+
