### ISSUE TITLE
Ausgabe von Code-Beispielen, Code-Highlighting in den CPT-Abschnitten Code

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-designsystem#22]
# Zielsetzung
Code-Highlighting soll zuverlässig die Codebeispiele im Designsystem highlighten. Das kopieren des Codes soll mit einem Button einfach und leicht möglich sein.

## Technische Anforderungen
- [x] Korrektes Code-Highlighting in den CPTs #21 
- [x] Ausgabe im Frontend bricht korrekt um 
- [x] Ausgabe der Zeilennummer (optional)
- [x] Kopieren der Code-Beispiele problemlos möglich

**Comment by thenickless** [comment]
Umgesetzt als eigenes Plugin, da unsere Kunden ein solches ebenso benötigen könnten.
RRZE-Typesettings
Verwendbar als Gutenberg Block oder als Shortcode.
Details siehe Readme: https://github.com/RRZE-Webteam/rrze-typesettings
