### ISSUE TITLE
Shortcode f. Code-Highlighting

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-designsystem#25]
# Was wird benötigt?
Ein Shortcode für Code-Highlighting, so dass er in #21 und #24 verwendet werden kann.

## Wieso erstmal ein Shortcode?
Damit er in den vielen Freitext-Bereichen der CPTs genutzt werden kann. Später in Version 2 Kann man überlegen, ob man zusätzlich einen Block bereitstellen möchte.

## Technische Anforderungen
- [x] Vgl. #22 
- [x] Falls nötig: Wahl der Programmiersprache als Attribut
- [x] Übergabe des Code-Snippets
- [x] Code-Ausgabe muss kopierbar sein vgl. #22

**Comment by thenickless** [comment]
Umgesetzt als eigenes Plugin, da unsere Kunden ein solches ebenso benötigen könnten.
RRZE-Typesettings
Verwendbar als Gutenberg Block oder als Shortcode.
Details siehe Readme: https://github.com/RRZE-Webteam/rrze-typesettings
