### ISSUE TITLE
Feste Taxonomien für Posttype 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-designsystem#3]
Dem Posttype sind einer Design-System-Taxonomy zuzuordnen, die fest ist un daus folgenden Elementen besteht:
- Components
- Patterns
- Design Tokens
- Utilities
- Templates

Vergleichbar dem Beispiel von hier:
https://designsystem.digital.gov/

Ggf. könnten diese Typen auch in Form von Custom Field Post Templates umgesetzt werden anstelle von klassischen Taxonomien.

Die beste Lösung kann während der Umsetzung überlegt werden.

**Comment by lukasniebler** [comment]
Wie gestern besprochen umgeworfen
