### ISSUE TITLE
Subnavigation in Post Type 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-designsystem#5]
Es sollte in Erwägung gezogen werden, eine Subnavigation anzubieten, die den Inhalt des Post Types betrifft.
Da wir ja definierte Datenfelder haben, sollte dies leicht machbar sein.

Beispiel wie hier (rechte Seite): 
https://designsystem.digital.gov/components/combo-box/

**Comment by lukasniebler** [comment]
In #21
