### ISSUE TITLE
Live Beispiele

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-designsystem#6]
Bei manchen EIngaben werden Live-Beispiele gewünscht.
Zwar sollte theoretisch das CMS das Design System selbst berücksichtigen und daher diese durch das eigene HTML/Shortcodes umsetzen können, jedoch kann es auch Felder oder Beispiele geben, die sich nicht leicht im WordPress nachstellen lassen.

Daher ist für solche Fälle ein Embed von Codepen zu überleben.

Ggf. braucht es daher ein weiteres EIngabefeld zur Einbindung von Codepen im POstType.

Beispiel:
https://css-tricks.com/making-tables-with-sticky-header-and-footers-got-a-bit-easier/

Hier gibt es Beispiele mit Embeddings von Codepen.

**Comment by lukasniebler** [comment]
Für v2+
