### ISSUE TITLE
Info: Designsysteme zum Vergleich

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-designsystem#8]
In diesem "Issue" sollen geeignete Designsysteme gesammelt werden, damit man sich hiervon inspirieren lassen kann und es auch klarer ist, was dieses Plugin leisten soll.
Bitte diesen Issue daher nicht als "erledigt" schließen, solange wir nicht eine stabile produktive Version ausgerollt haben.

### U.S. Web Design System (USWDS)
- LIve: https://designsystem.digital.gov/
- GitHub: https://github.com/uswds/uswds

### California Design System
- Live: https://designsystem.webstandards.ca.gov/
- GitHub: https://github.com/cagov/design-system

### Storybook
- https://storybook.js.org/#automate

### Atlassian Design System
- https://atlassian.design/

### Material Design
- https://m2.material.io/design 

### Apple HUman Interface Guidelines
- https://developer.apple.com/design/human-interface-guidelines

## Auch hilfreich zum Thema Designsysteme:
- https://www.designsystemchecklist.com/ 
- https://www.knapsack.cloud/calculator
- https://webdevstudios.com/2020/02/20/design-systems-for-wordpress/

**Comment by thenickless** [comment]
### evernote : Design Systems

- https://www.evernote.design/categories/design-systems/

Viele Designsysteme. Hervorstechend ist mMn W3C: https://design-system.w3.org/templates/group-details.html
